[package]
name = "predict"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3"  # MIT or Apache-2.0
vaporetto = { path = "../vaporetto", features = ["multithreading"] }  # MIT or Apache-2.0
