[package]
name = "convert_kytea_model"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "~4.0.2", features = ["derive"] }  # MIT or Apache-2.0
vaporetto = { path = "../vaporetto", features = ["kytea"] }  # MIT or Apache-2.0
zstd = "0.11"  # MIT
